import { NextRequest, NextResponse } from "next/server";
import { PDFDocument, StandardFonts, rgb } from "pdf-lib";

export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    const {
      dairy,
      customer,
      invoiceNumber,
      dateFrom,
      dateTo,
      deliveryItems,
      customItems,
      totalDeliveryAmount,
      totalCustomAmount,
      grandTotal,
      totalPaid,
      balanceDue,
    } = body;

    const pdfDoc = await PDFDocument.create();
    const page = pdfDoc.addPage([595, 842]);
    const font = await pdfDoc.embedFont(StandardFonts.Helvetica);
    const fontBold = await pdfDoc.embedFont(StandardFonts.HelveticaBold);

    const margin = 50;
    let y = 800;
    const lineHeight = 16;
    const pageWidth = 595;

    const drawText = (text: string, x: number, yVal: number, size: number = 10, isBold: boolean = false) => {
      const f = isBold ? fontBold : font;
      page.drawText(text, { x, y: yVal, size, font: f, color: rgb(0.1, 0.1, 0.1) });
    };

    const drawLine = (startX: number, yVal: number, endX: number) => {
      page.drawLine({ start: { x: startX, y: yVal }, end: { x: endX, y: yVal }, thickness: 0.5, color: rgb(0.8, 0.8, 0.8) });
    };

    // Header
    drawText(dairy.name || "Dairy", margin, y, 18, true);
    y -= lineHeight;
    if (dairy.address) { drawText(dairy.address, margin, y, 9); y -= lineHeight; }
    if (dairy.phone) { drawText(`Phone: ${dairy.phone}`, margin, y, 9); y -= lineHeight; }

    // Invoice title right side
    drawText("INVOICE", pageWidth - margin - 70, 800, 16, true);
    drawText(`#${invoiceNumber}`, pageWidth - margin - 70, 800 - lineHeight, 9);
    drawText(`Date: ${new Date().toLocaleDateString()}`, pageWidth - margin - 100, 800 - lineHeight * 2, 8);

    drawLine(margin, y, pageWidth - margin);
    y -= 20;

    // Bill To
    drawText("BILL TO", margin, y, 9, true);
    y -= lineHeight;
    drawText(customer.name, margin, y, 11, true);
    y -= lineHeight;
    if (customer.phone) { drawText(`Phone: ${customer.phone}`, margin, y, 9); y -= lineHeight; }
    if (customer.address) { drawText(customer.address, margin, y, 9); y -= lineHeight; }
    y -= 10;

    drawText(`Period: ${dateFrom} to ${dateTo}`, margin, y, 9);
    y -= 20;

    // Table header
    drawLine(margin, y, pageWidth - margin);
    y -= 5;
    drawText("Description", margin + 5, y, 9, true);
    drawText("Qty", margin + 250, y, 9, true);
    drawText("Rate", margin + 310, y, 9, true);
    drawText("Amount", margin + 390, y, 9, true);
    y -= 5;
    drawLine(margin, y, pageWidth - margin);
    y -= 15;

    const allItems = [...(deliveryItems || []), ...(customItems || [])];
    for (const item of allItems) {
      if (y < 100) {
        pdfDoc.addPage([595, 842]);
        y = 800;
      }
      const desc = (item.description || "").length > 40 ? (item.description || "").substring(0, 40) + "..." : (item.description || "");
      drawText(desc, margin + 5, y, 8);
      drawText(`${item.quantity}L`, margin + 255, y, 8);
      drawText(`Rs.${(item.rate || 0).toFixed(2)}`, margin + 300, y, 8);
      drawText(`Rs.${(item.amount || 0).toFixed(2)}`, margin + 380, y, 8);
      y -= lineHeight;
    }

    y -= 5;
    drawLine(margin, y, pageWidth - margin);
    y -= 20;

    if (totalDeliveryAmount > 0) {
      drawText("Delivery Total:", margin + 280, y, 9);
      drawText(`Rs.${totalDeliveryAmount.toFixed(2)}`, margin + 380, y, 9);
      y -= lineHeight;
    }
    if (totalCustomAmount > 0) {
      drawText("Additional Items:", margin + 280, y, 9);
      drawText(`Rs.${totalCustomAmount.toFixed(2)}`, margin + 380, y, 9);
      y -= lineHeight;
    }

    drawLine(margin + 270, y, pageWidth - margin);
    y -= 5;
    drawText("Grand Total:", margin + 280, y, 10, true);
    drawText(`Rs.${grandTotal.toFixed(2)}`, margin + 380, y, 10, true);
    y -= lineHeight * 1.5;

    if (totalPaid > 0) {
      drawText("Payments Received:", margin + 280, y, 9);
      drawText(`Rs.${totalPaid.toFixed(2)}`, margin + 380, y, 9);
      y -= lineHeight;
      drawText("Balance Due:", margin + 280, y, 10, true);
      drawText(`Rs.${balanceDue.toFixed(2)}`, margin + 380, y, 10, true);
    }

    drawLine(margin, 60, pageWidth - margin);
    drawText("Thank you for your business!", margin, 45, 8);
    drawText(`Generated by Dairy Ledger on ${new Date().toLocaleString()}`, margin, 30, 7);

    const pdfBytes = await pdfDoc.save();

    return new NextResponse(pdfBytes, {
      status: 200,
      headers: {
        "Content-Type": "application/pdf",
        "Content-Disposition": `attachment; filename="${invoiceNumber}.pdf"`,
      },
    });
  } catch (error) {
    console.error("PDF generation error:", error);
    return NextResponse.json({ error: "Failed to generate PDF" }, { status: 500 });
  }
}
